### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by pxslip**
- Update the Queue UI for maybe better usability? Still poking at it
- Need to add UI to support non-chat based editing of commands

### CODE REVIEW

**Comment by pxslip** [comment]
Initial UI, sticking with a pretty basic nav paradigm. Top level pages, left side tools, right side block of content. Sticking with a grayscale color palette for now, but pretty easy to swap that around if we settle on a color scheme.

image

I am getting to the point where we need to decide what pages the admin UI should support. I feel like having the command list is a good one (what actions should that support, create, edit, delete?). and the queue of course. Anything else you can think of for an initial release?

**Comment by trollham** [comment]
I think everything you mention is a good start. The command module should have the ability to create, disable, edit, and delete commands (which will need support on the API side to actually expose the command interface; at the moment it's only available through chat). The queue, obviously, but I'm thinking chat would be good to have at this stage too.

**Comment by pxslip** [comment]
Hah, I was finishing up last night when I realized that chat would be important to have on screen. Going to end up moving some UI elements around to get chat in there somehow (probably collapsible, but will cross that bridge when I come to it).

**Comment by trollham** [comment]
I was entertaining the idea of chat being a collapsible drawer on the right of the window, like how twitch itself displays it

**Comment by pxslip** [comment]
Updated Screenshots

With chat open:

image

With chat collapsed:

image

**Comment by trollham** [comment]
This PR has begun to get unwieldy in size as time's gone on. Could we bring it back down and split this work across a few, more easily reviewable branches? We could leave this one as the UI and Tailwind changes, and split the OBS websockets and other work across a different branch.

**Comment by pxslip** [comment]
Yeah...had the same thought the other day. Of course I then proceeded to merge a bunch of work into this branch without thinking last night. Will do some branching and reverting to try to cut this branch back and get a few other ones in place.

**Comment by pxslip** [comment]
In an attempt to make this PR less unwieldy I've reset this branch back to what I think is the most logical place for it. I pulled out the initial TS conversion work and opened a PR on my fork targeting this branch (`ui-updates`) and then opened a new branch and PR (also on my fork) to handle the conversion to pinia. Unfortunately the three PRs are dependent, so the pinia work needs to be merged into the typescript conversion before merging all of that into the ui-updates. Hopefully that makes some amount of sense given my slightly sleep deprived brain.

TS Conversion PR: https://github.com/pxslip/brittlq/pull/2
Pinia Conversion PR: https://github.com/pxslip/brittlq/pull/3

(Why Pinia: https://twitter.com/youyuxi/status/1463429442076745730?t=n1RJ5BydUGOr5rS_fA8iWA, basically Vue has new recommended libraries, now seemed like the time to convert, API is nicer, plus I guess pinia === vuex, just some issues with naming 🤷🏻 )

**Review by trollham — APPROVED** [review]

**Pull request merged**
